name: hadith
description: This dart plugin provides access to the Hadith data offline.
version: 1.0.1
homepage: https://github.com/aqeelshamz/hadith
repository: https://github.com/aqeelshamz/hadith

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0